export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(git)
source $ZSH/oh-my-zsh.sh

autoload -U compinit && compinit
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

alias primetime='watch -t -n 1 "factor $(date +%s)"'
alias copy="xclip -selection copy"

export MOZ_DISABLE_GMP_SANDBOX=1
export EDITOR=vim
alias copy="xclip -selection copy"
#export LD_LIBRARY_PATH=~/.guix-profile/lib:/run/current-system/profile/lib

export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"
export PATH=$PATH:/home/laura/.local/bin:/usr/local/bin:/home/laura/.cargo/bin:/home/laura/.config/hypr/scripts:/run/current-system/profile/libexec/fwupd

if [ -f /run/current-system/profile/bin/guix ]; then
    export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"
    export GUIX_PROFILE="$HOME/.guix-profile"
    . ~/.guix-profile/etc/profile
else
    if [ -f /etc/alpine-release ]; then
        export PS1="(alpine) $PS1"
        unalias grep
    else
        export PS1="($(cat /etc/os-release | grep ^ID | cut -d"=" -f2)) $PS1"
        if [ -f "$HOME/.cargo/env" ]; then
            . "$HOME/.cargo/env"
        fi  

        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"

        export PATH="$PATH:/usr/lib/git-core"
        unset CURL_CA_BUNDLE GIT_SSL_CAINFO NIX_SSL_CERT_FILE SSL_CERT_DIR SSL_CERT_FILE
        export EDITOR=vim
    fi  
fi

alias primetime='watch -t -n 1 "factor \$(date +%s)"'
alias xmlfmt="xmllint --format -"
export LLVM_COMPILER=clang
export MPLBACKEND=qtagg
export CC=clang
export IPFS_PATH=/ipfs_data
