export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(git)
source $ZSH/oh-my-zsh.sh

autoload -U compinit && compinit
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

export MOZ_DISABLE_GMP_SANDBOX=1
export EDITOR=vim
export LLVM_COMPILER=clang
export MPLBACKEND=qtagg
export CC=clang
export IPFS_PATH=/ipfs_data
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"
export BORG_REPO=/home/laura/borg
export PATH=$PATH:/home/laura/.local/bin:/usr/local/bin:/home/laura/.cargo/bin:/home/laura/.config/hypr/scripts:/run/current-system/profile/libexec/fwupd:/run/privileged/bin

if [ -f /run/current-system/profile/bin/guix ]; then
    export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"
    export GUIX_PROFILE="$HOME/.guix-profile"
    . ~/.guix-profile/etc/profile
else
    if [ -f /etc/alpine-release ]; then
        export PS1="(alpine) $PS1"
        unalias grep
    else
        export PS1="($(cat /etc/os-release | grep ^ID | cut -d"=" -f2)) $PS1"
        if [ -f "$HOME/.cargo/env" ]; then
            . "$HOME/.cargo/env"
        fi  

        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"

        export PATH="$PATH:/usr/lib/git-core"
        unset CURL_CA_BUNDLE GIT_SSL_CAINFO NIX_SSL_CERT_FILE SSL_CERT_DIR SSL_CERT_FILE
        export EDITOR=vim
    fi  
fi
